name: check and build

on: [push, pull_request]

jobs:
  build:
    name: Making it

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Getting node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: Looking for crap code
        run: npm run lint

      - name: Running unit tests
        run: npm test

      - name: Building prod
        run: npm run build

      - name: Building dev
        run: npm run build-dev

      - name: Archiving prod
        uses: actions/upload-artifact@v2
        with:
          name: webapp-prod
          path: dist/

      - name: Archiving dev
        uses: actions/upload-artifact@v2
        with:
          name: webapp-dev
          path: dev/
